<a href="https://colab.research.google.com/github/monalAJ/-practice-Dealing-with-missing-values/blob/main/Dealing_With_missing_Values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/AB_NYC_2019.csv")

In [4]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,1,0

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48906 entries, 0 to 48905
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48906 non-null  int64
 1   name                            48890 non-null  object
 2   host_id                         48906 non-null  int64
 3   host_name                       48885 non-null  object
 4   neighbourhood_group             48906 non-null  object
 5   neighbourhood                   48906 non-null  object
 6   latitude                        48906 non-null  float64
 7   longitude                       48906 non-null  float64
 8   room_type                       48906 non-null  object
 9   price                           48906 non-null  int64
 10  minimum_nights                  48906 non-null  int64
 11  number_of_reviews               48906 non-null  int64
 12  last_review                     38854 non-null  object
 13  reviews_per_month               38854 non-null  float64
 14  calculated_host_listings_count  48906 non-null  int64
 15  availability_365                48906 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [5]:
ddf = df.copy()

In [7]:
ddf

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48901,5441,Central Manhattan/near Broadway,7989,Kate,Manhattan,Hell's Kitchen,40.76076,-73.98867,Private room,85,2,188,23-06-2019,1.50,1,39
48902,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,89,4,167,24-06-2019,1.34,3,314
48903,6021,Wonderful Guest Bedroom in Manhattan for SINGLES,11528,Claudio,Manhattan,Upper West Side,40.79826,-73.96113,Private room,85,2,113,05-07-2019,0.91,1,333
48904,6090,West Village Nest - Superhost,11975,Alina,Manhattan,West Village,40.73530,-74.00525,Entire home/apt,120,90,27,31-10-2018,0.22,1,0
48905,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.70837,-73.95352,Entire home/apt,140,2,148,29-06-2019,1.20,1,46

In [8]:
ddf.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,1,0

In [9]:
ddf.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365'],
      dtype='object')

In [10]:
ddf.shape

(48906, 16)

In [11]:
ddf.isnull().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [ ]:
ddf.drop("last_review", axis = 1 , inplace = True)

In [15]:
ddf.isnull().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

**Deleting the row with missing values**

In [16]:
ddf = df.copy()

In [17]:
ddf.isna().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [19]:
ddf.dropna(inplace = True)

In [20]:
ddf.isna().sum()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [21]:
ddf.shape

(38832, 16)

**Filling the Missing Values - Imputation**

**1) Numerical data - use mean**

In [39]:
ddf2 = df.copy()

In [40]:
ddf2.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,1,0

In [41]:
mean_values = ddf2["reviews_per_month"].mean()

ddf2["reviews_per_month"].fillna(mean_values, inplace = True)

In [42]:
ddf2.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.210000,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.380000,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,1.373151,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.640000,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.100000,1,0

In [43]:
ddf2.isnull().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                     0
calculated_host_listings_count        0
availability_365                      0
dtype: int64

**Filling Categorical data**

In [44]:
ddf2.nunique()

id                                48895
name                              47896
host_id                           37457
host_name                         11452
neighbourhood_group                   5
neighbourhood                       221
latitude                          19048
longitude                         14718
room_type                             3
price                               674
minimum_nights                      109
number_of_reviews                   394
last_review                        1764
reviews_per_month                   938
calculated_host_listings_count       47
availability_365                    366
dtype: int64

In [45]:
ddf2["last_review"].value_counts()

23-06-2019    1414
01-07-2019    1359
30-06-2019    1341
24-06-2019     877
07-07-2019     718
              ...
31-12-2012       1
29-05-2014       1
06-06-2014       1
25-12-2012       1
29-03-2018       1
Name: last_review, Length: 1764, dtype: int64

In [46]:
ddf2["last_review"].fillna(ddf2["last_review"].value_counts().index[0], inplace = True)

In [47]:
ddf2.isnull().sum()

id                                 0
name                              16
host_id                            0
host_name                         21
neighbourhood_group                0
neighbourhood                      0
latitude                           0
longitude                          0
room_type                          0
price                              0
minimum_nights                     0
number_of_reviews                  0
last_review                        0
reviews_per_month                  0
calculated_host_listings_count     0
availability_365                   0
dtype: int64

In [36]:
ddf3 = df.copy()

In [37]:
ddf3.isna().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [48]:
ddf3["last_review"].fillna("Not Reiviewed", inplace = True)

In [50]:
ddf3.sample(20)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
40677,31557578,Cozy room next to subways and Prospect Park,227134858,Hitalo,Brooklyn,Prospect-Lefferts Gardens,40.66238,-73.94289,Private room,58,1,8,30-06-2019,1.56,5,158
20399,16275767,Spacious sun lit Bushwick room,106451051,Claire,Queens,Ridgewood,40.70338,-73.91006,Private room,40,5,8,03-08-2017,0.26,1,6
2272,1087215,Stunning Designer Loft in the heart of Chelsea,1841580,George,Manhattan,Chelsea,40.74877,-73.99940,Entire home/apt,300,5,44,03-07-2019,0.62,1,87
47333,35692073,Prime location! 5BR with 3BA Townhouse + Patio!,268207118,Rosaline,Manhattan,Midtown,40.75959,-73.96473,Entire home/apt,279,3,2,22-06-2019,2.00,1,244
30011,23106106,Homey townhouse apartment,32718658,Mia,Manhattan,East Harlem,40.80017,-73.93812,Private room,70,1,0,Not Reiviewed,NaN,1,0
22933,18579690,HOUSE WITH 2 ENTRANCES 15min TO MANHATTAN,30237517,David,Queens,Forest Hills,40.73412,-73.85090,Entire home/apt,278,2,16,12-07-2018,0.62,6,0
45725,34933648,Sonder | 116 John | Bright 1BR + Rooftop,219517861,Sonder (NYC),Manhattan,Financial District,40.70782,-74.00616,Entire home/apt,137,29,0,Not Reiviewed,NaN,327,341
10182,7801783,Private 2 Bedroom Apartment in the East Village,2033003,Darren,Manhattan,East Village,40.72935,-73.98465,Entire home/apt,200,2,6,08-04-2019,0.13,2,134
15713,12700609,Doorman Gym W&D RoofDeck!5112,16098958,Jeremy & Laura,Manhattan,Upper West Side,40.79613,-73.96638,Entire home/apt,197,30,2,31-07-2017,0.06,96,104
14718,11637578,Spacious and sunny room for rent,61684714,Grace,Manhattan,Washington Heights,40.84248,-73.93849,Private room,26,7,0,Not Reiviewed,NaN,1,0
34446,27316669,Bronx Apart,205820814,Luz,Bronx,Highbridge,40.83454,-73.92751,Private room,10,1,0,Not Reiviewed,NaN,1,180
13503,10104123,East Village Bedroom w/Roof Deck,51850937,Joe,Manhattan,East Village,40.73061,-73.98335,Private room,100,2,51,02-07-2019,1.19,3,4
40262,31221589,Elegance and Comfort in Clinton Hill,646563,Brian,Brooklyn,Clinton Hill,40.68162,-73.96083,Private room,75,1,3,28-05-2019,1.70,2,0
24299,19568889,Comfy Guest room+private bathroom+ 300ft to Tr...,137512725,Kiki,Manhattan,Harlem,40.82555,-73.94297,Private room,77,2,36,16-06-2019,1.49,1,116
1305,568684,800sqft apartment with huge terrace,2798644,Alessandra,Brooklyn,Bushwick,40.70202,-73.92402,Entire home/apt,115,370,6,15-04-2018,0.09,1,365
3621,2169106,Huge Sunny Room In Awesome Apt/Neighborhood,11066377,Brett,Brooklyn,Prospect-Lefferts Gardens,40.65910,-73.96116,Private room,100,2,13,19-05-2019,0.36,1,365
15168,12110990,Amazing 2 BR NYC apt. with up-to-date amenities!,30283594,Kara,Manhattan,Midtown,40.76657,-73.98201,Entire home/apt,369,30,1,30-10-2018,0.12,121,345
20488,16321597,Great room in charming Fort Greene Brooklyn,26004891,Ariane,Brooklyn,Fort Greene,40.69357,-73.97235,Private room,44,6,0,Not Reiviewed,NaN,1,0
28214,21971593,Private newest room in Bushwick.,146345538,Sergii,Brooklyn,Bushwick,40.69475,-73.91507,Private room,50,30,1,04-10-2018,0.11,5,361
6396,4659285,Manhattan! Bunk beds for 10+,23334165,Patricia,Manhattan,Harlem,40.82396,-73.94388,Entire home/apt,450,5,81,09-06-2019,1.48,3,303

**Advanced Imputation**

In [54]:
ddf4 = df.copy()

In [55]:
ddf4.isnull().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [56]:
ddf4.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,1,0

In [57]:
ddf4["reviews_per_month"].interpolate(inplace = True)

In [58]:
ddf4.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,2.51,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,1,0